language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
install:
- sudo apt-add-repository ppa:wpilib/toolchain -y
- sudo apt update -q
- sudo apt install frc-toolchain -y
script: ./gradlew :wpilibj:wpilibJavaJNISharedLibrary && stat wpilibj/build/binaries/wpilibJavaJNISharedLibrary/libwpilibJavaJNI.so
notifications:
  slack:
    secure: JBdO5C0B1yp0qaoLWwKlf/kDlxOtDGXtPt4P48U03z9QTg/i/8JRvjxTbBdiGFAo7mU7DdKiGWy0KhLSkMhWWOms+/SEiZel7XEXaG7bi6938a1I9tWrQi3EztDefVerOzBbHAFIUx+fRmaWuNd4mMZQXqC2xRfPjbP+HMvymnGfkpz9hSB7KmYs7HJ38ugygPS1dAlyBT5M2GY/PfSESBZNt8vA7q6yF3d835N/Vvhj9T3t2LbSJim8W0DEG854j5QKOADCZhDeifPouphYN51qeZlGdwMOpwRY5B15bjm3pQseaJWgx+Mdl9Qfva99oYMcbNE1DKMzRBkAYLNP6d94daoWBluRSb9Hc91VQjhE5qf3U7iaDRX8QeLyM0Agq1OVim3QdXW/vzmSj9CuzxaYQ9MzHD0lOSXLiJadKVZhYnqsrm6zuX78wpMVLvmeVV+DS20x8bC30nXSn5jbOW1XH0YUKkxw2DLX+0FRMdmra42LNJfZEGdVAfv2wMZ1bCsHhN0AdQR3B1L6rcpyOyReAm4cmmmY+w1XYBfJu3lpdJHQj+U5ZYCnXcsfk/HUf9cvTv7xpxARuO0L1V3R5WsaQgiDnAKm/OxIZwBzs9+UdJ1RjCEIkh98+dflMuCk6AdHRmMfCLCISy+PY4rZ8s7/7wi8R/j2slut3jX4pJ4=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: T/6RVa4hvO3VNrkiztSIMEx9i5Cbf0sc4zXmGLbIOA57HIKiNjYaaXsW/QPdREicqRJNBmpg6xTiECnq2eI18gtGT8lc8cbE2ePBcjpxAy5ZrrXjMcd5X3rIAo1nTBEgbK1vYPVCsPamDjG5qb4IqEf5GV+wP7O0nYZwLlsXSXExxK6ZBgqIOWu1hgKjcGaEGVBy+nmtxvF+m7x4PdEhFb68RHK09YKjaY+iiFxOQPnQYInrafgjIn7sY4IKmpUrU6TpcJVo6QfFZkW7Z2JPRSHeVWDpsPsJNV5IsIRaSzPqx8K9aHlGejL3sMmkpOVU9jogk1TPs410C+oNDA/YyH+d20/lltEbp6kmOWPrVVvAX7/ao9G2lGszTZbyZyeOjGPlVs0vS9ZbEVFAqjXGvR90MzXzFKCf2cU1uXTvVQ35O8+JtTWjfT8+MV3fXt/swTexTuDRcOyA2rzEoh6RAipc55knyLA3dPv+XpT58ZK0573D7QXLGlZ/6R54W+RL0aWtjrWpq1bgWQhtIPtxDW304scTiPs8uQdnaL99DWZa5ApSO7HkLNn4OziaB0HOAUAAUU9HlDBg6+7slVGezyFkdo5tXi9bmsi14Jg1UOTIvDvWM2rwPDZKWRyCwdevtheRl6o8sYv4jVd1P2GRyhgUsaehj8DyDENEcaPb1Ms=
  file: wpilibj/build/binaries/wpilibJavaJNISharedLibrary/libwpilibJavaJNI.so
  on:
    tags: true
    repo: flamingchickens1540/wpilib-mirror
    all_branches: true
