language: java
jdk:
- oraclejdk8
sudo: false
script: ./gradlew :wpilibj:wpilibJavaJNISharedLibrary && stat wpilibj/build/binaries/wpilibJavaJNISharedLibrary/libwpilibJavaJNI.so
notifications:
  slack:
    secure: QHYkPTjA1v9Ml9Tr4Oc9GC/tQYxNNvf7uFKUZmpHhcH9zhlFwM8z4dXrNllYoq7R5sgQga9+bKr69zIwDOiFDQ/EQK6QNL7T66hKbpStuM+GqZ+PS+px/CpmiErpk7A8gvXAqBKLU82kswTxafjW0g8dlmbVEFctyykf3nOYQjY=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eav0qCnVMp92Xi2KBICIF9Tfh4HRHqJsQk3zgJ6NLlfykIZ5NF8j1jtYs0o3Dq1W6vPvORdmgQynbptXjQUHWIKxIbwwQG4m8lpz4KXermBrrg72VF29S23BsMRozuYsHcqwQT/KIYVc/ZpBubMuWbRpxWDT0TgAIyaBCWiiW0I=
  file: wpilibj/build/binaries/wpilibJavaJNISharedLibrary/libwpilibJavaJNI.so
  on:
    tags: true
    repo: flamingchickens1540/wpilib-mirror
    all_branches: true
